rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category,
                    name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page,
                    name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('restricted/', views.restricted, name='restricted'),
    path('search/', views.search, name='search'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
# from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('', views.index, name='index'),
    path('', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args,**kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self) -> str:
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Page, self).save(*args,**kwargs)

    def __str__(self) -> str:
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self) -> str:
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Category, Page, User, UserProfile
import re

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                            help_text='Please enter the category name.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text='Please enter the title of the page.')
    url = forms.URLField(max_length=200,
                        help_text='Please the URL of the page.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        # exclude = ('category', 'views')
        fields = ('title', 'url')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        url = re.sub(r"http[s]:[\/]+","", url)
        if url:
            url = f'https://{url}'
            cleaned_data['url'] = url
        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rango/views.py
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm
from rango.forms import UserForm, UserProfileForm
from rango.search import run_query


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['aboldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    visitor_cookie_handler(request)

    response = render(request, 'rango/index.html', context=context_dict)
    return response


def show_category(request, category_name_slug):
    context_dictionary = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dictionary['pages'] = pages
        context_dictionary['category'] = category
    except Category.DoesNotExist:
        context_dictionary['category'] = None
        context_dictionary['pages'] = None
    return render(request, 'rango/category.html', context=context_dictionary)


def about(request):
    # if request.session.test_cookie_worked():
    #     print('TEST COOKIE WORKED!')
    #     request.session.delete_test_cookie()
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = get_server_side_cookie(request, 'visits', 1)
    return render(request, 'rango/about.html', context=context_dict)


@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('/')
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    if category is None:
        return redirect(reverse('rango:index'))
    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category',
                                        kwargs={'category_name_slug':
                                                category_name_slug}))
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            # hash the password
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,
                  'rango/register.html',
                  context={'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse('Your Rango account is disabled.')
        else:
            print(f'Invalid login details: {username}, {password}')
            return HttpResponse('Invalid login details supplied.')
    else:
        return render(request, 'rango/login.html')


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit', str(datetime.now()))
    # last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).days > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits


def search(request):
    query = ""
    result_list = []
    if request.method == 'POST':
        query = request.POST['query'].strip()
    if query:
        # Run our Bing function to get the results list!
        result_list = run_query(query)
    return render(request, 'rango/search.html', {'result_list': result_list})

rango/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}About{% endblock %}
{% block body_block %}
    <p>
        <h1>Rangos says...</h1>
        here is the about page.
    </p>
    <div>
        <img src="{% get_media_prefix %}cat.webp" alt="picture of Rango and her"><br />
    </div>
    <p>
        This tutorial have been put together by Camila Pua   
    </p>
    <div>
        <p>Visits: {{ visits }}</p>
    </div>
{% endblock %}

rango/templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% block title_block %}Add a category{% endblock %}

{% block body_block %}
    <h1>Add a Category</h1>
    <div>
        <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}<br>
            {% endfor %}
            <input type="submit" name="submit" value="Create Category"/>
        </form>
    </div>
{% endblock %}

rango/templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% block title_block %}Add a page{% endblock %}

{% block body_block %}
    <h1>Add a Page in {{category}}</h1>
    <div>
        <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}<br>
            {% endfor %}
            <input type="submit" name="submit" value="Add Page"/>
        </form>
    </div>
{% endblock %}

rango/templates/rango/base-old.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rango - 
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
    <style>
        /* Estilo para el footer */
        footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            background-color: #333;
            color: #fff;
            text-align: center;
            padding: 10px;
        }
        /* Estilo para los enlaces en el footer */
        footer a {
            color: #fff;
            text-decoration: none;
            margin: 10px;
        }
    </style>
</head>
<body>
    <div>
        {% block body_block %}
            This is the body_block's default content.
        {% endblock %}
    </div>
    <div>
        {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
    </div>
    <br>
    <footer>
        <a href="{% url 'rango:index' %}">Homepage</a>
        <a href="{% url 'rango:about' %}">About</a>
        <a href="{% url 'rango:add_category' %}">Add a New Category</a>
        <a href="{% url 'rango:restricted' %}">Restricted page</a>
        {% if user.is_authenticated %}
            <a href="{% url 'auth_logout' %}?next={% url 'rango:index'%}">Logout</a><br />
            <a href="{% url 'auth_password_change' %}">Change password</a>
        {% else %}
            <a href="{% url 'registration_register' %}">Sign up</a>
            <a href="{% url 'auth_login' %}">Login</a>
        {% endif %}
    </footer>
</body>
</html>

rango/templates/rango/base.html
{% load static %}
{% load rango_template_tags %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>{% block title_block %}How to Tango with Django!{% endblock %}</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/dashboard/">

    <link href="https://getbootstrap.com/docs/5.3/dist/css/bootstrap.min.css" rel="stylesheet"
        crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <meta name="theme-color" content="#712cf9">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.comddocs/5.3/dashboard.css" rel="stylesheet">
</head>

<body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="{% url 'rango:index' %}">Rango</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-nav">
            <div class="nav-item text-nowrap">
                <ul>
                    {% if user.is_authenticated %}
                    <!-- Show these links when the user is logged in -->
                    <a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a>
                    {% else %}
                    <!-- Show these links when the user is NOT logged in -->
                    <a href="{% url 'registration_register' %}">Sign Up</a>
                    <a href="{% url 'auth_login' %}">Login</a>
                    {% endif %}
                </ul>
            </div>
        </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3 sidebar-sticky">

                    {% block sidebar_block %}
                    {% get_category_list category %}
                    {% endblock %}
                    <!--
        <ul class="nav flex-column">
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="home" class="align-text-bottom"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file" class="align-text-bottom"></span>
              Orders
            </a>
          </li>
        </ul>
  -->

                    <h6
                        class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
                        <span>Links</span>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'rango:add_category' %}">
                                <span data-feather="file-text" class="align-text-bottom"></span>
                                Add New Category
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'rango:about' %}">
                                <span data-feather="file-text" class="align-text-bottom"></span>
                                About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'rango:search' %}">
                                <span data-feather="file-text" class="align-text-bottom"></span>
                                Search</a>
                        </li>
                        {% if user.is_authenticated %}
                        <!-- Show these links when the user is logged in -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'rango:restricted' %}">
                                <span data-feather="file-text" class="align-text-bottom"></span>
                                Restricted Page</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auth_password_change' %}">
                                <span data-feather="file-text" class="align-text-bottom"></span>
                                Change Password</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div
                    class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <!--        <h1 class="h2">Dashboard</h1>  -->
                    {% block body_block %}
                    {% endblock %}
                </div>
            </main>
        </div>
    </div>
    <footer>
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2023 Tango With Django 4 &middot;</p>
    </footer>
    <script src="https://getbootstrap.com/docs/5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
        crossorigin="anonymous"></script>
    <script src="https://getbootstrap.com/dashboard.js"></script>
</body>

</html>

rango/templates/rango/categories.html
<ul class="nav flex-column">
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
                    <span data-feather="archive"></span>{{ c.name }}
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
                    <span data-feather="archive"></span>{{ c.name }}
                </a>
            </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li class="nav-item">There are no categories present.</li>
    {% endif %}
</ul>

rango/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    {% if category %}
        {{ category }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    <div>
        {% if category %}
            <h1>{{ category.name }}</h1>

            {% if pages %}
                <ul>
                    {% for page in pages %}
                        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>No pages currently in category.</strong>
            {% endif %}

            {% if user.is_authenticated %}
                <a href="{% url 'rango:add_page' category.slug %}">Add a page</a>
            {% endif %}

        {% else %}
            The specified category does not exist.
        {% endif %}
    </div>
{% endblock %}

rango/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}Homepage{% endblock %}

{% block body_block %}
<div>
    <div class="container-fluid py-3">
        <div class="row bg-light rounded-3">
            <h1 class="display-5 fw-bold">Rango says...</h1>
            <p class="col-md-8 fs-4">
                {% if user.is_authenticated %}
                    howdy {{ user.username }}!
                {% else %}
                    hey there partner!
                {% endif %}
            </p>
            <div>
                <img src="{% static 'images/rango.jpg' %}" />
            </div>
            <strong>{{ aboldmessage }}</strong>
        </div>
    </div>
    <div>
        <h2>Most Liked Categories</h2>
        {% if categories %}
            <ul>
                {% for category in categories %}
                    <li><a href="{% url 'rango:show_category' category.slug %}">{{ category }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
    </div>
    <div>
        <h2>Most Viewed Pages</h2>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="page/{{ page.slug }}/">{{ page }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no pages present.</strong>
        {% endif %}
    </div>
</div>
{% endblock %}

rango/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />
        <input type="submit" value="submit" />
    </form>
{% endblock %}

rango/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for you registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a>
    {% else %}
        Rango says: <strong>register here!</strong>
        <form id="user_form" action="{% url 'rango:register' %}" method="post" enctype="multipart/form-data"> 
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="submit" value="Register"/>
        </form>
    {% endif %}
{% endblock %}

rango/templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}Restricted Page{% endblock %}

{% block body_block %}
    <h3>Howdy {{ user.username }}</h3>
    Since you're logged in, you can see this text!
{% endblock %}

rango/templates/rango/search.html
{% extends 'rango/base.html' %}
{% load static %}
{% block title_block %}
    Search
{% endblock %}
{% block body_block %}
<div class="container-fluid py-3">
    <div class="row bg-light rounded-3">
        <h1 class="display-5 fw-bold">Search with Rango</h1>
    </div>
    <div class="row py-5">
        <form class="row g-3"
                id="user-form"
                method="post"
                action="{% url 'rango:search' %}">
            {% csrf_token %}
            <div class="col-auto">
                <label class="visually-hidden">Search</label>
                <input type="text" readonly class="form-control-plaintext"
                value="Enter your search terms">
            </div>
            <div class="col-auto">
                <label class="visually-hidden">Search</label>
                <input type="text" class="form-control" id="query"
                placeholder="Search" name="query">
            </div>
            <div class="col-auto">
                <button type="submit" name="submit"
                class="btn btn-primary mb-3">Search</button>
            </div>
        </form>
    </div>
    <div class="row py-5">
        {% if result_list %}
            <h2>Results</h2>
            <div class="list-group">
            {% for result in result_list %}
                <div class="list-group-item">
                    <h3 class="list-group-item-heading">
                    <a href="{{ result.link }}">
                        {{ result.title|safe|escape }}
                    </a>
                    </h3>
                    <p class="list-group-item-text">
                        {{ result.snippet|safe|escape }}
                    </p>
                </div>
            {% endfor %}
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}